version: "3.9"  # optional since v1.27.0
services:
  test:
    image: golang:1.18
    volumes:
      - .:/code
      - /tmp/go:/go
    working_dir: /code
    command: bash -c "pwd && go get -d -v && go test -v ./..."
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: experiment
    logging:
      driver: none
